//Quse : 01

// let a = 10;
// document.write("The value of a is : " + " " + a + "<br>");
// ++a;
// document.write(`<br><br>The value of ++a is : ${a}. <br>`);
// document.write(`Now the value of a is: ${a}. <br>`);

// document.write(`<br><br>The value of a++ is : ${a}. <br>`);
// a++;
// document.write(`Now the value of a is: ${a}. <br>`);

// --a;
// document.write(`<br><br>The value of --a is : ${a}. <br>`);
// document.write(`Now the value of a is: ${a}. <br>`);

// document.write(`<br><br>The value of a-- is : ${a}. <br>`);
// a--;
// document.write(`Now the value of a is: ${a}. <br>`);

//Ques: 02

// let a = 2;
// let b = 1;
// document.write(`a is: ${a}. <br>`);
// document.write(`b is: ${b} . <br>`);
// let result = --a - --b + ++b + b--;
// document.write(`Result : ${result}. <br>`);

//Ques : 03

// let userInput = prompt("user name?")
// document.write(`<br> Hello ${userInput}`);

//Ques: 04

// let tableNo = prompt("Table no?");
// if (tableNo == ""  ) {
//     for (let i = 1; i <= 10; i++) {
//         console.log(`5 x ${i} = ${5 * i}`);
//       }
// } else {
//     for (let i = 1; i <= 10; i++) {
//         console.log(`${tableNo} x ${i} = ${tableNo * i}`);
//       }
// }

//Ques: 06
// document.write("<h1>Subject &emsp; Total Marks &emsp; Obtained Marks &emsp; Percentage</h1>");

// let subj1 = prompt("Enter the first subject");
// let subj2 = prompt("Enter the second subject");
// let subj3 = prompt("Enter the third subject");

// let totalMarks = 100;

// let subj1ObtMarks = (prompt(`Enter obtained marks for ${subj1}`));
// let subj2ObtMarks = (prompt(`Enter obtained marks for ${subj2}`));
// let subj3ObtMarks = (prompt(`Enter obtained marks for ${subj3}`));


// let subjOnePercentage = (subj1ObtMarks / totalMarks) * 100;
// let subjTwoPercentage = (subj2ObtMarks / totalMarks) * 100;
// let subjThreePercentage = (subj3ObtMarks / totalMarks) * 100;

// document.write(`<br>${subj1} &emsp; ${totalMarks} &emsp; ${subj1ObtMarks} &emsp; ${subjOnePercentage.toFixed(1)}%<br>`);
// document.write(`<br>${subj2} &emsp; ${totalMarks} &emsp; ${subj2ObtMarks} &emsp; ${subjTwoPercentage.toFixed(1)}%<br>`);
// document.write(`<br>${subj3} &emsp; ${totalMarks} &emsp; ${subj3ObtMarks} &emsp; ${subjThreePercentage.toFixed(1)}%<br>`);



//Ques: 07


